dist: bionic

sudo: required

git:
  depth: 3

os: linux
language: minimal

env:
   global:
     - PROGRESS_TYPE=plain

cache:
  timeout: 60

addons:
  hosts:
    - yves.de.spryker.local
    - zed.de.spryker.local
    - glue.de.spryker.local
  apt:
    packages:
      - apache2-utils
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - pigz
      - software-properties-common
    sources:
      - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        key_url: https://download.docker.com/linux/ubuntu/gpg

before_install:
  - echo eyAiZXhwZXJpbWVudGFsIiA6IHRydWUsICJmZWF0dXJlcyIgOiB7ICJidWlsZGtpdCI6IHRydWUgfSB9Cg==|base64 -d|sudo tee /etc/docker/daemon.json
  - sudo apt-get install --only-upgrade docker-ce -y
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo systemctl start docker

matrix:
  fast_finish: true
  allow_failures: []
  include:
    - name: Demo boot test
      env: DEV_MODE=0
      script:
        - bash ./ci/check_boot.sh
    - name: Dev boot test
      env: DEV_MODE=1
      script:
        - bash ./ci/check_boot.sh
    - name: Demo Bash syntax check
      env: DEV_MODE=0
      script:
        - bash ./ci/check_bash_syntax.sh
    - name: Demo Bash syntax check
      env: DEV_MODE=1
      script:
        - bash ./ci/check_bash_syntax.sh
    - name: Tests
      script:
          - bash ./ci/tests.sh
      before_install: skip
      before_script: skip
      after_script: skip
    - name: Deploy file builder tests
      language: php
      php: 7.4
      script:
        - cd generator
        - composer install
        - vendor/bin/codecept run
    - name: Docker / B2C Demoshop / PHP-7.4 Alpine / MariaDB / Functional
      env:
        - SPRYKER_PLATFORM_IMAGE=spryker/php:7.4-alpine3.14
        - TRAVIS=1
        - APPLICATION_ENV=ci.mysql
        - SPRYKER_TESTING_ENABLED=1
        - APPLICATION_STORE=DE
        - PROJECT=suite
      script:
        - cd ../ && git clone --depth=3 --branch=master https://github.com/spryker-shop/b2c-demo-shop.git demo-shop && mv docker-sdk demo-shop && cd demo-shop
        - docker-sdk/sdk boot deploy.ci.functional.mariadb.yml -v
        - docker-sdk/sdk up -t -v
        - docker-sdk/sdk testing codecept run -c codeception.ci.functional.yml
      before_script: skip
      after_script: skip
    - name: Docker / B2C Demoshop / PHP-7.4 Debian / PostgreSQL / Functional
      env:
          - SPRYKER_PLATFORM_IMAGE=spryker/php:7.4-debian
          - TRAVIS=1
          - APPLICATION_ENV=ci.pgsql
          - SPRYKER_TESTING_ENABLED=1
          - APPLICATION_STORE=DE
          - PROJECT=suite
      script:
          - cd ../ && git clone --depth=3 --branch=master https://github.com/spryker-shop/b2c-demo-shop.git demo-shop && mv docker-sdk demo-shop && cd demo-shop
          - docker-sdk/sdk boot deploy.ci.functional.yml -v
          - docker-sdk/sdk up -t -v
          - docker-sdk/sdk testing codecept run -c codeception.ci.functional.yml
      before_script: skip
      after_script: skip
    - name: Docker / B2B Demoshop / PHP-7.4 Alpine / PostgreSQL / Functional
      env:
          - SPRYKER_PLATFORM_IMAGE=spryker/php:7.4-alpine3.15
          - TRAVIS=1
          - APPLICATION_ENV=ci.pgsql
          - SPRYKER_TESTING_ENABLED=1
          - APPLICATION_STORE=DE
          - PROJECT=suite
      script:
          - cd ../ && git clone --depth=3 --branch=master https://github.com/spryker-shop/b2b-demo-shop.git demo-shop && mv docker-sdk demo-shop && cd demo-shop
          - docker-sdk/sdk boot deploy.ci.functional.yml -v
          - docker-sdk/sdk up -t -v
          - docker-sdk/sdk testing codecept run -c codeception.ci.functional.yml
      before_script: skip
      after_script: skip
    - name: Docker / B2B Demoshop / PHP-7.4 Debian / MariaDB / Functional
      env:
          - SPRYKER_PLATFORM_IMAGE=spryker/php:7.4-debian
          - TRAVIS=1
          - APPLICATION_ENV=ci.mysql
          - SPRYKER_TESTING_ENABLED=1
          - APPLICATION_STORE=DE
          - PROJECT=suite
      script:
          - cd ../ && git clone --depth=3 --branch=master https://github.com/spryker-shop/b2b-demo-shop.git demo-shop && mv docker-sdk demo-shop && cd demo-shop
          - docker-sdk/sdk boot deploy.ci.functional.mariadb.yml -v
          - docker-sdk/sdk up -t -v
          - docker-sdk/sdk testing codecept run -c codeception.ci.functional.yml
      before_script: skip
      after_script: skip

before_script:
  - chmod +x sdk
  - if [[ $DEV_MODE == 0 ]] ; then ./sdk boot ci/deploy.yml; fi
  - if [[ $DEV_MODE == 1 ]] ; then ./sdk boot ci/deploy.dev.yml; fi

notifications:
  email: false

